# Http Server Listen Address
listen = "[::]:7777"

[[ice_servers]]
urls = [
    "stun:stun.l.google.com:19302"
]

# [[ice_servers]]
# urls = [ "turn:turn.22333.fun", "turn:cn.22333.fun" ]
# username = "livestream707"
# credential = "livestream707"

# WHIP/WHEP auth token
#Headers["Authorization"] = "Bearer {token}"
# [auth]
#tokens = ["livestream707"]

# Not WHIP/WHEP standard
# https://developer.mozilla.org/en-US/docs/Web/HTTP/Authentication#basic
# Headers["Authorization"] = "Basic {Base64.encode({username}:{password})}"
# [[auth.accounts]]
# username = "livestream707"
# password = "livestream707"

# [log]
# Env: `LOG_LEVEL`
# Default: info
# Values: off, error, warn, info, debug, trace
# level = "warn"
