[http]
# Http Server Listen Address
listen = "[::]:8888"
# Cross-Origin Resource Sharing (CORS)
# reference: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS
cors = false

[[ice_servers]]
urls = [
    "stun:stun.22333.fun",
    "stun:cn.22333.fun",
    "stun:stun.l.google.com:19302",
]

# [[ice_servers]]
# urls = [ "turn:turn.22333.fun", "turn:cn.22333.fun" ]
# username = "livestream707"
# credential = "livestream707"

# WHIP/WHEP auth token
# Headers["Authorization"] = "Bearer {token}"
#[auth]
#tokens = ["eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ935A","SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJVAR25f"]

# Not WHIP/WHEP standard
# https://developer.mozilla.org/en-US/docs/Web/HTTP/Authentication#basic
# Headers["Authorization"] = "Basic {Base64.encode({username}:{password})}"
[[auth.accounts]]
username = "superadmin"
password = "eyJhbGciOiJA54stf3IUzI1NiIsInR5cCI6IkpXVCJ935A707"

# [log]
# Env: `LOG_LEVEL`
# Default: info
# Values: off, error, warn, info, debug, trace
# level = "warn"

[database]
host = "localhost"
port = "3306"
username = "root"
password = "Workanaciaob2xbet@"
dbname = "webrtc_streaming"


