FROM rust:slim-bookworm as builder

RUN apt-get update && \
    apt-get install -y pkg-config && \
    apt-get install -y libudev-dev && \
    apt-get install -y libglib2.0-dev && \
    apt-get install -y libssl-dev

WORKDIR /app

COPY . .

RUN cargo build --release
FROM debian:bookworm-slim

COPY --from=builder /app/config-dist.toml /etc/livestream707/config.toml
COPY --from=builder /app/target/release/livestream707 /usr/local/bin/livestream707

CMD ["livestream707"]

